In [2]:
import numpy as np

In [3]:
array1d = np.array([1, 2, 3, 4, 5])

In [4]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [7]:
# Acceder a un elemento del array
print(array1d[0])

# Acceder al último elemento del array
print(array1d[-1])

1
5


In [13]:
# Acceder a un elemento de un array 2D
print(array2d[0, 2])
print(array2d[1, 2])
print(array2d[1][2])

# Acceder a una fila de un array 2D
print(array2d[0])

3
6
6
[1 2 3]


In [30]:
# Slicing de un array 1D
print(array1d[1:3])
print(array1d[:3])

# Slicing de un array 2D
print(array2d[1, :]) # Obtener la fila 2

[2 3]
[1 2 3]
[4 5 6]


In [26]:
print(array2d[1, 1:3])

[5 6]


In [29]:
print(array2d[:, 1]) # Obtener la columna 2

[2 5 8]


In [32]:
print(array2d[1:, 1:])

[[5 6]
 [8 9]]


In [36]:
# Indiexación boolean
print(array1d[array1d > 2]) # Obtener los elementos mayores a 2

print(array2d[array2d % 2 == 0]) # Obtener los elementos pares

[3 4 5]
[2 4 6 8]


### Ejercicios

In [38]:
import numpy as np

nunmeros = np.array(list(range(1, 11)))
quinto_elemento = nunmeros[4]
print(quinto_elemento) # 5

5


In [39]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
segunda_fila = matriz[1]
print(segunda_fila) 

[4 5 6]


In [ ]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

pares_impares = matriz % 2 == 0
print(pares_impares)

[[False  True False]
 [ True False  True]
 [False  True False]]
