In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array.shape

(9,)

In [4]:
array_mod = array.reshape(3, 3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array_mod2 = array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array_transpose = array_mod.transpose()
array_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
array_unidim = array_mod.flatten() # Crea una copia
array_unidim

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_ravel = array_mod.ravel() # Devuelve una vista
array_ravel

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ejercicios

In [15]:
import numpy as np
array_original = np.array(list(range(1, 13)))
array_reshape = array_original.reshape(3, 4)
array_reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
import numpy as np
array_original = np.array([[1,2,3], [4,5,6]])
array_modificado = array_original.T
array_modificado

array([[1, 4],
       [2, 5],
       [3, 6]])

In [18]:
import numpy as np
array_original = np.array([[1,2,3], [4,5,6]])
array_aplanado = array_original.ravel()
array_aplanado

array([1, 2, 3, 4, 5, 6])