In [1]:
import numpy as np

In [5]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [6]:
array2 = np.array([[0], [10], [20], [30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [7]:
broadcast_suma  = array1 + array2
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [8]:
broadcast_multiplicacion = array1 * array2
broadcast_multiplicacion

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [9]:
# Expresiones universales: Funciones que operan sobre arrays pero aplicando la operación a cada elemento.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
resultado = np.add(a, b)
print(resultado)
print(type(resultado))

[5 7 9]
<class 'numpy.ndarray'>


In [13]:
resultado = np.subtract(a, b)
print(resultado)

resultado = np.multiply(a, b)
print(resultado)

resultado = np.divide(a, b)
print(resultado)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
resultado = np.exp(a)
print(resultado)

resultado = np.sqrt(a)
print(resultado)

resultado = np.log(a)
print(resultado)

resultado = np.log10(a)
print(resultado)

resultado = np.sin(a)
print(resultado)

resultado = np.cos(a)
print(resultado)

resultado = np.tan(a)
print(resultado)

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


In [18]:
a = np.array([1.22, 2.56, 3.78])

resultado = np.floor(a)
print(resultado)

resultado = np.ceil(a)
print(resultado)

[1. 2. 3.]
[2. 3. 4.]


In [122]:
# Estadísticas
lista_random = np.random.randint(1, 100, 75)
a = np.array(lista_random)
print(f"Datos: {a}\n")

resultado = np.sum(a)
print(f"Suma: {resultado}\n")

resultado = np.mean(a)
print(f"Media: {resultado}\n")

resultado = np.std(a)
print(f"Desviacion estandar: {resultado}\n")

resultado = np.var(a)
print(f"Varianza: {resultado}\n")

resultado = np.min(a)
print(f"Minimo: {resultado}\n")

resultado = np.max(a)
print(f"Maximo: {resultado}\n")

resultado = np.median(a)
print(f"Mediana: {resultado}\n")

print("Cuartiles:")
resultado = np.percentile(a, 25)
print(resultado)
resultado = np.percentile(a, 50)
print(resultado)
resultado = np.percentile(a, 75)
print(resultado)
resultado = np.percentile(a, 100)
print(resultado)

Datos: [91 33 89 34  2 39  5 85  4 63 94 12 89 39 85 58 52 61 68 63 95  7 19 12
 88 86 13 35 64 24 44 77 67 30 33 76 65 76 81  7 56 45 71  4 56 36 46 67
 11 56 19 47  3 32 43 70 83 61 83 99 11 10 65  4 42  6 41 90 67 47 44 47
 20 22 16]

Suma: 3585

Media: 47.8

Desviacion estandar: 28.653795560099883

Varianza: 821.0399999999998

Minimo: 2

Maximo: 99

Mediana: 47.0

Cuartiles:
21.0
47.0
69.0
99.0


### Ejercicios

In [4]:
import numpy as np
A = np.array(list(range(1, 10, 2)))
B = np.array(
    [
        [10],
        [20],
        [30],
        [40],
        [50]
    ]
)

resultado = A + B
print(resultado)

[[11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]]


In [6]:
import numpy as np
A = np.array(list(range(1, 11)))
B = np.array(
    [
        [10],
        [20],
        [30],
        [40],
        [50]
    ]
)

resultado = A * B
print(resultado)

[[ 10  20  30  40  50  60  70  80  90 100]
 [ 20  40  60  80 100 120 140 160 180 200]
 [ 30  60  90 120 150 180 210 240 270 300]
 [ 40  80 120 160 200 240 280 320 360 400]
 [ 50 100 150 200 250 300 350 400 450 500]]


In [8]:
import numpy as np
A = np.array(list(range(1, 4)))

resultado = np.exp(A)
print(resultado)

[ 2.71828183  7.3890561  20.08553692]
