In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,np.nan,5,6,7])
array

array([ 1.,  2.,  3., nan,  5.,  6.,  7.])

In [3]:
np.isnan(array)

array([False, False, False,  True, False, False, False])

In [4]:
np.mean(array) # Me devuelve un nan porque hay un NaN en el array

nan

In [5]:
np.nanmean(array) # Ignora el NaN y me devuelve la media de los demás elementos

4.0

In [6]:
np.nansum(array) # Ignora el NaN y me devuelve la suma de los demás elementos

24.0

## Diferentes maneras de tratar los datos faltantes con numpy

In [8]:
array_con_0 = np.where( np.isnan(array), 0, array) # Cambia el NaN por un 0
array_con_0

array([1., 2., 3., 0., 5., 6., 7.])

In [10]:
promedio = np.nanmean(array) # Calcula la media ignorando el NaN
print(promedio)
array_con_promedio = np.where( np.isnan(array), promedio, array) # Cambia el NaN por la media
array_con_promedio

4.0


array([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
array_filtrado = array[ ~np.isnan(array)] # Filtra el array y elimina los NaN
array_filtrado

array([1., 2., 3., 5., 6., 7.])

### Ejercicios

In [14]:
import numpy as np

array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan])

nan_presencia= np.isnan(array)
nan_presencia

array([False,  True, False,  True, False, False,  True])

In [15]:
import numpy as np

array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan]) 

promedio_sin_nans = np.nanmean(array) # Calcula la media ignorando los NaN
print(promedio_sin_nans)

3.625


In [16]:
import numpy as np

array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan])

sustituir_nans = np.where(np.isnan(array), 0, array) # Cambia los NaN por 0
print(sustituir_nans)

[3.  0.  7.  0.  0.  4.5 0. ]
