# Proyecto del Día 8 - Análisis de Datos Meteorológicos

Este proyecto consiste en analizar un conjunto de datos meteorológicos utilizando Python y NumPy. 
El objetivo es aplicar las técnicas de manipulación de arrays, tratamiento de datos faltantes, 
y análisis estadístico básico en un conjunto de datos del mundo real.

## Tareas a Realizar:
1. Crear un DataFrame a partir de los datos del archivo **datos_meteorologicos.csv** provisto en esta lección.
2. Realizar observaciones iniciales de los datos con Pandas.
3. Convertir las columnas del DataFrame en arrays de NumPy.
4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.
5. Realizar análisis estadísticos básicos. Mínimamente se espera que puedas extraer la siguiente información de tus arrays:
    * La temperatura promedio
    * El total de precipitaciones
    * La máxima humedad registrada
    * La fecha más calurosa
    * La fehca más fría
6. Exportar los resultados a un nuevo archivo CSV.

¡Mucha suerte con tu proyecto!


### 1. Crear un DataFrame a partir de los datos del archivo datos_meteorologicos.csv provisto en esta lección.

In [116]:
import numpy as np
import pandas as pd

In [117]:
df = pd.read_csv("./datos_meteorologicos.csv")
df.head()

Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530
2  03/01/2010    20.138169      15.317706  41.496715
3  04/01/2010    17.244159      13.151008  90.684704
4  05/01/2010    11.182740      16.413667  22.116422

### 2. Realizar observaciones iniciales de los datos con Pandas.

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [119]:
df.isnull().sum()

Fecha              0
Temperatura      255
Precipitación    255
Humedad          255
dtype: int64

In [120]:
df.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

### 3. Convertir las columnas del DataFrame en arrays de NumPy.

In [121]:
fecha = df["Fecha"].values
fecha

array(['01/01/2010', '02/01/2010', '03/01/2010', ..., '26/12/2023',
       '27/12/2023', '28/12/2023'], dtype=object)

In [122]:
temperatura = df["Temperatura"].values
temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

In [123]:
precipitacion = df["Precipitación"].values
precipitacion

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
               nan,  7.33051023])

In [124]:
humedad = df["Humedad"].values
humedad

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
               nan, 50.64621058])

### 4. Identificar los datos faltantes en los arrays, y reemplazarlos por el promedio de los valores del respectivo array.

In [125]:
promedio_temperatura = np.nanmean(temperatura)
print(f"Promedio de temperatura: {promedio_temperatura}")
temperatura = np.where(np.isnan(temperatura), promedio_temperatura, temperatura)

Promedio de temperatura: 14.889295723531715


In [126]:
promedio_precipitacion = np.nanmean(precipitacion)
print(f"Promedio de precipitación: {promedio_precipitacion}")
precipitacion = np.where(np.isnan(precipitacion), promedio_precipitacion, precipitacion)

Promedio de precipitación: 9.9016035987084


In [127]:
promedio_humedad = np.nanmean(humedad)
print(f"Promedio de humedad: {promedio_humedad}")
humedad = np.where(np.isnan(humedad), promedio_humedad, humedad)

Promedio de humedad: 54.35906079674394


In [128]:
# Comprobación de la longitud de los arrays
print(len(fecha))
print(len(temperatura))
print(len(precipitacion))
print(len(humedad))

5110
5110
5110
5110


### 5. Realizar análisis estadísticos básicos.

##### Temperatura promedio

In [129]:
temperatura_promedio = np.mean(temperatura)
print(f"Temperatura promedio: {temperatura_promedio}")

Temperatura promedio: 14.889295723531713


##### Total de precipitaciones

In [130]:
total_precipitacion = np.sum(precipitacion)
print(f"Total de precipitación: {total_precipitacion}")

Total de precipitación: 50597.19438939993


##### Máxima humedad registrada

In [131]:
max_humedad = np.max(humedad)
print(f"Máxima humedad: {max_humedad}")

Máxima humedad: 99.99658156071747


##### Fecha más calurosa

In [134]:
indice_maxima_temperatura = np.argmax(temperatura)
print(f"Índice de la máxima temperatura: {indice_maxima_temperatura}")

fecha_mas_calurosa = fecha[indice_maxima_temperatura]
print(f"Fecha más calurosa: {fecha_mas_calurosa}")

temperatura_maxima = np.max(temperatura)
print(f"Temperatura máxima: {temperatura_maxima}")

Índice de la máxima temperatura: 2749
Fecha más calurosa: 12/07/2017
Temperatura máxima: 39.99820092713012


##### Fehca más fría

In [135]:
indice_minima_temperatura = np.argmin(temperatura)
print(f"Índice de la mínima temperatura: {indice_minima_temperatura}")

fecha_mas_fria = fecha[indice_minima_temperatura]
print(f"Fecha más fría: {fecha_mas_fria}")

temperatura_minima = np.min(temperatura)
print(f"Temperatura mínima: {temperatura_minima}")

Índice de la mínima temperatura: 3856
Fecha más fría: 23/07/2020
Temperatura mínima: -9.996377518075391


### 6. Exportar los resultados a un nuevo archivo CSV.

In [136]:
array_general = np.concatenate((fecha.reshape(-1, 1), temperatura.reshape(-1, 1), precipitacion.reshape(-1, 1), humedad.reshape(-1, 1)), axis=1)
array_general

array([['01/01/2010', 17.440675196366236, 10.957481997233586,
        52.38463748841593],
       ['02/01/2010', 25.75946831862097, 5.3156276517729895,
        30.63352983123037],
       ['03/01/2010', 20.138168803582197, 15.317706093986718,
        41.49671457625978],
       ...,
       ['26/12/2023', 29.87359717232944, 4.61501176564858,
        18.362847375985744],
       ['27/12/2023', 14.889295723531715, 9.9016035987084,
        54.35906079674394],
       ['28/12/2023', 37.3080431767716, 7.33051023049333,
        50.646210575443774]], dtype=object)

In [ ]:
# Guardar datos corregidos en un nuevo archivo CSV
np.savetxt("./datos_meteorologicos_corregidos.csv", array_general, delimiter=",", fmt="%s")

In [139]:
# Guardar resultados
df = pd.DataFrame({
    "Métrica": ["Promedio de temperatura", "Total de precipitación", "Máxima humedad","Fecha más calurosa", "Temperatura máxima", "Fecha más fría", "Temperatura mínima"],
    "Valor": [promedio_temperatura, total_precipitacion, max_humedad, fecha_mas_calurosa, temperatura_maxima, fecha_mas_fria, temperatura_minima]
})
df.to_csv("./resultados.csv", index=False)