In [35]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
import pandas as pd

## MinMaxScaler para normalizar los datos entre 0 y 1

In [13]:
data = np.array([
    [1, -1, 2],
    [2, 0, 0],
    [0, 1, -1] 
])
print("Data antes de normalizar:")
print(data)

scaler = MinMaxScaler(feature_range=(0, 1))
data_normalizada = scaler.fit_transform(data)

print("\nData normalizada:")
print(data_normalizada)

Data antes de normalizar:
[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]

Data normalizada:
[[0.5        0.         1.        ]
 [1.         0.5        0.33333333]
 [0.         1.         0.        ]]


In [14]:
iris = load_iris()
X = iris.data

print("Data antes de normalizar:")
print(X[:5])

scaler = MinMaxScaler(feature_range=(0, 1))
data_normalizada = scaler.fit_transform(X)

print("\nData normalizada:")
print(data_normalizada[:5])

Data antes de normalizar:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Data normalizada:
[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


## StandardScaler para normalizar los datos con media 0 y desviación estándar 1

In [28]:
data = np.array([
    [1, -1, 2],
    [2, 0, 0],
    [0, 1, -1] 
])
print("Data antes de normalizar:")
print(data)

scaler = StandardScaler()
data_estandarizada = scaler.fit_transform(data)

print("\nData normalizada:")
print(data_estandarizada)

Data antes de normalizar:
[[ 1 -1  2]
 [ 2  0  0]
 [ 0  1 -1]]

Data normalizada:
[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [29]:
iris = load_iris()
X = iris.data

print("Data antes de normalizar:")
print(X[:5])

scaler = StandardScaler()
data_estandarizada = scaler.fit_transform(X)

print("\nData normalizada:")
print(data_estandarizada[:5])

Data antes de normalizar:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Data normalizada:
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


## OneHotEncoder para codificar variables categóricas

In [34]:
categorias = np.array([["rojo"], ["verde"], ["azul"], ["verde"], ["verde"], ["azul"]])
print(categorias)

encoder = OneHotEncoder(sparse_output = False)

data_codificada = encoder.fit_transform(categorias)

print("\nData codificada:")
print(data_codificada)

[['rojo']
 ['verde']
 ['azul']
 ['verde']
 ['verde']
 ['azul']]

Data codificada:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]]


### Ejercicios

In [39]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Datos originales
datos = np.array([[5, 15, 25],
                 [10, 20, 30],
                 [15, 25, 35]])

print("Datos originales:")
print(datos)

# Tu código aquí
scaler = MinMaxScaler(feature_range=(0, 1))
datos_normalizados = scaler.fit_transform(datos)

print("Normalizado")
print(datos_normalizados)

Datos originales:
[[ 5 15 25]
 [10 20 30]
 [15 25 35]]
Normalizado
[[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


In [43]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Datos originales
datos = np.array([[10, 2000, 30000],
                 [15, 3000, 50000],
                 [20, 4000, 70000]])

print("Datos originales:")
print(datos)

# Tu código aquí
scaler = StandardScaler()
datos_estandardizados = scaler.fit_transform(datos)

print("Estandarizado")
print(datos_estandardizados)

Datos originales:
[[   10  2000 30000]
 [   15  3000 50000]
 [   20  4000 70000]]
Estandarizado
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [48]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Datos originales
datos = np.array([['Rojo', 'Pequeño', 'Cítrico'],
                 ['Verde', 'Mediano', 'Dulce'],
                 ['Amarillo', 'Grande', 'Cítrico']])

print("Datos originales:")
print(datos)

# Tu código aquí
encoder = OneHotEncoder(sparse_output=False)
datos_codificados = encoder.fit_transform(datos)

print("Codificado")
print(datos_estandardizados)


Datos originales:
[['Rojo' 'Pequeño' 'Cítrico']
 ['Verde' 'Mediano' 'Dulce']
 ['Amarillo' 'Grande' 'Cítrico']]
Codificado
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
